"""new changes

Revision ID: e739509f89f9
Revises: 539124d403b2
Create Date: 2026-06-29 12:10:14.793720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e739509f89f9'
down_revision: Union[str, Sequence[str], None] = '539124d403b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('location', sa.String(), nullable=True))
    op.drop_constraint(op.f('companies_email_key'), 'companies', type_='unique')
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.drop_column('jobs', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.create_unique_constraint(op.f('companies_email_key'), 'companies', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('companies', 'location')
    # ### end Alembic commands ###
