"""initial

Revision ID: ed473d7d1eaa
Revises: 70c3111c1325
Create Date: 2026-07-07 15:25:16.430988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed473d7d1eaa'
down_revision: Union[str, Sequence[str], None] = '70c3111c1325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.create_unique_constraint(None, 'companies', ['email'])
    op.add_column('jobs', sa.Column('salary', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'salary')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    # ### end Alembic commands ###
